name: CI

on:
  push:
    branches: ['main', 'dev']
  pull_request:
    branches: ['main', 'dev']

jobs:
  frontend-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm ci

      - name: Check formatting
        run: npm run format:check

      - name: Lint
        run: npm run lint

      - name: Build
        run: |
          echo "Building project..."
          npm run build || {
            echo "Build failed. Attempting to fix Rollup issue...";
            npm install @rollup/rollup-linux-x64-gnu --save-dev;
            npm run build || { echo "Build failed after fix attempt"; exit 1; }
          }
